apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ftkshares-nfs-pvc.yaml
  - cloudflareddns/ks.yaml
  - jellyfin/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - tailscale/ks.yaml
  - kubernetes-dashboard/ks.yaml
