apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4gPfr+eJso64KZatpiJN+8tVrB2Ucaz0qWMoxeTtk0GhVUpuvm2WGPRJ8VFpTZGDCjjVpJ5kAWqfzW8JW67GxrHx92DstnLqVOjW9RUOHFtPlg90y9PdULNz1bny4GVMCDPgPWAmwWRz6oCxf9kNofE+G/tfspIrI33Q01ekahglHcyJjNa7tJfgjoTHx13jKB26w0lpKP2H8PnE8EAbiM+wYGC/YO30WSl+CBKCBUIKaihySoFOkdY22p/rJCAwt1d1j6xUhSLMsMrNPRPQI0w1XOSKzZxcyGtOEb2tYrPuyiYe2e5wcXq2QPV55JWkZVp7zoWGpwx1dff2O0yKnPSSjNcVQnsJoydP9wb182fhNo57gaG7kqvBISjt4U09,iv:x3UuJCWdOmQIeyDKwtd5jJK88dNH0SU7hbwPxqHHG78=,tag:6IzmqYYNNb/2ABnc45kuzA==,type:str]
    identity.pub: ENC[AES256_GCM,data:nHdBDy+GZ/0JnX8r3Erl4vj9Pp3XLlR1BOh2Q+AQ0Fs8wMX2FrVT4RuGBHcUhjSzhgrZiA7chxcIKxR1SzkjnGIqtp6ADI/hn9V2QvHw50pRtwQBL93zUz/xWavUldLnYfHDJOjdFuhvtbrj+k3fsVVB4g5VJFpLYeQVg2B99j0ybxjr1S0Gwap/z6sbWDmWZy6zOITJvkM087ttvzsgEQt2nAhB5mnhd8nDyx8APjOVM59J52lHlK+UB5jD9hnolNl+AXxsU3sUGvxlrQ==,iv:AiSDFTLptPIGgxivIEfrjZwrWqHlZEz4Kn48ukhUz3o=,tag:uSQVhEcUs421bKBhC77Bfg==,type:str]
    known_hosts: ENC[AES256_GCM,data:8wZecq/QKzgEVaDaUqUHb1pcRKb4XVtQUcl/R0mkiK8MHOm68MPCweoJ0ADtz/mR6JSmmcXaJC/6UPquqqmEnrYWKLxeDrB4V+g62wZLsrxoj3hIu4+hcbIcJy++xxxgcg/2Ce4nAbHY1vPodUG/xasSlqkyAhyB+lqRKBrwj9FQhB8m6rtTTaBr86XUU/PST7z9OY3HirXh3phFc6llI7uwGP4hRKPCNpL9,iv:qjLZkaCRVk3wupPC4pZjGvT/nqAGLMapM6mzXAjPYnY=,tag:V0L8RCyUOysxk2vTTCossg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY241VEFFVm1BYjZWNDVW
            Y0VYUXVrZTc0bElGUzZJaHhiOU5yVVN4TWxNCm9lTXNnb3Zrc2JDQllGNGQvdTU0
            MnRobXY0ejJDR2VzMk8xV3VlM2ZNTlEKLS0tIFJaTkpmcXJvUGw0aWxVS0dSWDhR
            NmE5ZUtBaFV1MWdGdWxCS0pKbGZPWVEKlflxlg7B+HMQdgpkAnTtm+ZSn+COT+Bv
            buaOUZZf/Cno7nTeqagc6bqfIITcg8jef6ZUSMNFhxJi3OwmFFiR2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18e6ndkyv6hedmhxvrlz0m5hpq9rly6gknvlez8s7el33uah9v4asyt25ks
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-12T21:17:35Z"
    mac: ENC[AES256_GCM,data:xdsqy6HqEzv9/aqn1ahCbk47XFWxlArd43y27sBqsfY66MrdxRS5EiimlU2v4s8vbUmFGjVmRoxwMXzKaPmwvg5WfJJWhSMZME9O+algaK8kLsTV9MPYRYSiKNtRwxR8b6Di+VioPAiaKZme4xM7jNOXg9Yz2wwHUSUSNp4JWQw=,iv:Rk55GpoWpiNXXi5SZOS3d2M4ks44ahWQqFAIhJpoZFw=,tag:iniZCZoEfbVeqf4vFz06+w==,type:str]
    shamir_threshold: 3
    version: 3.13.1
