apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:U0htjHFa3UVnSb2GhcI48OLC4PWquCwI5YiP0F427SHl8aQnfsQVMs8xC71zOtCirfvga2/7zGmqKJ8B4tMZQR9VQ2JvLz8k/rveSq384x5+q/w/D+3vPc7WhYpxKaZjx5s6hkSJrMVR7veCkkUa4FypE7CAWqse8XtjD0xgzUxzfUAxmuOiD1brkpcwQftESVddUdeRx1VvxyuhxAqXk/1TFDvmnWJ3SfUAq0sYFXXFI+40RN429WfgF7TTL/SYnDd5DFEbwVNMIF/O5fe7zN4qcOIQ33alJVAceQVnkUAyhYAB6pgvecms1S4OOWRFPURsgpq2IeDfd651AcboEdQOn4JcfA8L6yOo9EuCL2ncq2UvwmxSWD/ZvQbt+M9r,iv:oaf1mw2/5g7LI9uqw/bzhkZFeAUJpDZZRdIzMM7/WD0=,tag:oVPD2NP3DmonuvL97ajydg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Gfta27myUtEjuDP16qfDcEuPyr1xdoy1H8fT0tPDNGZmhA1E1QocUZBw28Kv4ZFIZNASnbwSeHZehEQIi6USb52RAky+6n4lNAZ1FnMf7DArJsBkSwa1XvnDoYbkU0FZiFvL/OrGTvYQztknMawkpaayL81x8wjeuM2BXp1GE6FkvKnZ6GRtMYvSyfyO676y9vq1o0qJhXgFw1590fOFUgYWx9VcOU0u1DMTYKc0tqnDwXT9Hq7lK8J5fQ1NWltuZlXbiV46g7iuop6pgw==,iv:QqU+Sn1SyBv24CtJhcz8jerHUb9db3s23RxaKrE2/YQ=,tag:kxvfji2rqquOD3X3/pRxvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:xnGZHaZzCe8uVj1xg3OncPzwm48P7Si6dHwP8rwa/PHwpIa8RtrgifSDXaKIdi5oKnVhEBnOKP9B4Vnj6RYiEUjj89qIjRoD46Ji1Tv+DvvnwwpJFNnakz/pxq0IWpQvxkRGcw3OTa1kA6TuI9Xm/ze9RTAHMZFnrKcmtapFHU0yrJtV2/zHINTaJaLz4Wykew6uSz4s0O8dLj0z1NwMdX1dPg/+XQ7rm4I4,iv:WlU/HMKJGf0ZWsIiWszIritW0GYWyzuaUz4TE2jtjck=,tag:7/LuHD8XUHs8madb6udN6g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVmc4dEdjenVhVHBaVG9x
            UnY1VVFFWEhKQlV5bllrWkZjc0NDSFhwWWprCjhDNXo0ZmhxWkZHNEMrLytYTW5r
            Nnk4SGhTbTNrdXVpR1A2L3VtUVNkdXMKLS0tIEZES0p2WWYvU1k1MElobVlhcGRW
            dlFQK2NnRVlLbkF4OGNVWjdsU2pqWEUKsbhyBG8lK682srIV8W7W4hgsotXA+ohf
            uT9lqIa+xHnIacPdh53EdzjukbFlxhkwICaA46gn0xO4iMeGe69ojQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18e6ndkyv6hedmhxvrlz0m5hpq9rly6gknvlez8s7el33uah9v4asyt25ks
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-13T23:04:04Z"
    mac: ENC[AES256_GCM,data:eqNNttcbvZm+kzdBFn3IFh2NYbF4lRAPZY+H4vqubni6Led+r2Pmm1yQl3sFJgs+WeT2RbJBVwnz6iwZOd080i8cUxPBI4l6CHGPsC0GSTyJ+9qMeWVY3UITVXlYeBJzZSuUYUl8QpoWmeESJC4jHnJcF3D7z+9VkfsuXnPrflk=,iv:D8oF8aBRVOyKeEvDpqmvTKwvraBDsqEC53uwgjNIpJQ=,tag:bd4kUFICn9JOk7hciUKTAg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
