apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uT1CkBkbqs8RG8X5xVp89WVsn0+RsdOCA/PuKY65xvhZ9+B+0vIudy9lBk0SMHz9PV03ioPctR9wLMgXDuPbA4HzpRJJMSOXeCQ6AIwGbU8QYHsPpO4+rwvDyLnFeQ4vUZWQrK0+WJoWXxSTmhqZoqu882OvXmaF+dIjWIgc6veFjpoKXOCiEY+mk0+3yYrhWYet3hiHwxIinssphvHNMRDyCeXnCHYQ1svKxpifd7Wzs5mqwaTD7ozvjSxBEzVD1MYX+A80NC/JnNHHCeutut2av0q+C3veOGW5K/3pyGmt//gmzt76VMf4hv1MuhJs4iCIAg+WC23F5G2rFi/xSPA/M7VnSOkoXwoHxVxV/p1B/Soo1DjBxzA2cw6B4bxx,iv:hrKJDgidvEGWs100GTzduU7jFc5Yru8EhSMR3WBxOdE=,tag:Wfv8kv/gmGvMfp0rPjb4ww==,type:str]
    identity.pub: ENC[AES256_GCM,data:6+75NfojfBkCLTmZf17pdn4ndwmQzfm3Rbm++ZeHpJDHy53RIZX7JaFIHs1p+9RdZpOHPVk+W5G+JdiHp2GZ9xXOayNs4xOJrVVCxZGuPuC/66c6zmYnShhvxKSsMy7BAxd1PgmMe51oX1x+9f1ql+RVZtVHDZEN5PHCFDm3o1amVJdEjMQz06bSt/ElNYwKhGAysnOXXeMpyC6CUrrodiDLL708OaLge9x8E4zMeXfWcursdliIcTN/LV6J9a3OKlerxqf1utWkZR4+MA==,iv:ayWgzhBucgTi+/xMBW6WBHmlXAlvi+h1rT7DTSmYK/Y=,tag:E8DSeFIU/KJ57r8Zv/Fyew==,type:str]
    known_hosts: ENC[AES256_GCM,data:uhcYUG/BX/7zUKc2FHzK+n5vNcwG1P28Eur5BKWWAJO3nGzxW52U2ae79blOzCcGBAK9WWGoSImVAlYzPiaC1L3q+TUhNkd1IMW7qREeWY7OT8Aavnz3NJCH8bdbVtR0AFdH+E2Df2U/XbraPdbhprSCidROBZ+o9L8CfHDL4UMXGiqTXL4s/hreBI7MH+ahLEhpCqmtQdteXUvlI86ZJz9svpbhHoeqxLze,iv:KwssokDWsJ+Mx0SQGw/pVTklHo+op6AVM0TiGr7jeyk=,tag:2JOyd1usHAqOWr39j7wOCw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbVM0S0lNbFZaVzVob3Fm
            UTQ2MnQzbTF4Z0h2S3VzNDFPRzZ3cjhhVkhNCjRKaFRudEsrdE5ySWlnWFpuNDZT
            K2h5ZGNOTWNmazJMcTdXcGVsUFMzR28KLS0tIG1GMUpwbHQvbUJDWGFSTlhyR2Jt
            QmpldUNOY3pvSk4vL3J3NFhmNVI4dFkKfszv+6BaMyb9HGwvOMWtr+XRGV+T0n7y
            hRkci677A17EdUQGLFh1IN+QErk4Ajf2KTG0W5993OZ9+tAkKHb0DQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18e6ndkyv6hedmhxvrlz0m5hpq9rly6gknvlez8s7el33uah9v4asyt25ks
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-12T01:42:49Z"
    mac: ENC[AES256_GCM,data:LRFC6VnuDX1I358eLv9BNFlR9cY2O6x2JjD8J3w/KK2klSMM7gA2q5xSksb31khpbqLP7fwYhO0+Q9+nhX5nyZfO7bmCIld+Aj6WEU880DGePryUzFdq+gaUip72aaWjBq0R7Pwu1WQ3eJwqPctDG1R8AmBHGI4QIvJuCmowxXQ=,iv:z8N6CtEc8k9OEfp7NPk+F54z7aB1q4YxLvVbZT7miO0=,tag:JrbVlm3qTJF/QMqhZDPJ5Q==,type:str]
    shamir_threshold: 3
    version: 3.13.1
