apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 21.12.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    credentials:
      cloudflare-r2:
        accessKey: "${CLOUDFLARE_R2_ACCESS}"
        bucket: jellyfin-scale
        encrKey: "${CLOUDFLARE_R2_ENCRKEY}"
        name: cloudflare-r2
        path: ""
        secretKey: "${CLOUDFLARE_R2_SECRET}"
        type: s3
        url: "${CLOUDFLARE_R2_URL}"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: jelly.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
          traefik:
            enabled: false
    persistence:
      config:
        volsync:
          - credentials: cloudflare-r2
            dest:
              enabled: true
            name: config
            src:
              enabled: true
            type: restic
      streaming:
        enabled: true
        type: nfs
        path: /mnt/FTKStreaming/Streaming
        server: 192.168.0.2
        mountPath: /streaming
      media:
        enabled: true
        type: nfs
        path: /mnt/FTKShares/Media
        server: 192.168.0.2
        mountPath: /FTKSRV/Media
    resources:
      limits:
        cpu: 16000m